### ISSUE TITLE
Списки сайтов, которые блокируют доступ для русских IP

### ISSUE THREAD

**Issue by vit9696** [gSpotx2f/ruantiblock_blacklist#2]
Добрый день,

Можно дополнительно добавить список сайтов, которые самостоятельно ограничивают доступ для IP-адресов из России? Сейчас я веду такой список самостоятельно, но было бы удобнее, если бы он находился в одном месте и постепенно пополнялся совместными усилиями.

В качестве начального содержимого значений могу предложить следующие домены:

```
ajax.aspnetcdn.com
analog.com
bits.avcdn.net
compsoc.eu
cydiaimpactor.com
dell.com
desipro.de
digikey.com
freescale.com
freesmug.org
ghidra-sre.org
hp.com
intel.com
intuitibits.com
lenovo.com
linksysinfo.org
macpaw.com
microfocus.com
microsoft.com
nxp.com
qt.io
qualcomm.com
quora.com
themoviedb.org
weather.com
wikidot.com
```

UPD: Обновлено в соответствии с комментариями.

Спасибо!

**Comment by gSpotx2f** [comment]
Создание дополнительного списка требует внимания для поддержания актуальности, проверок и пр. Честно говоря, у меня нет на это времени. Данный скрипт просто автоматизирует процесс получения списка блокировок из реестра, дополнительные сайты уже немного выходят за рамки этого проекта. Если необходимо добавить собственные хосты, то можно индивидуально использовать `user_entries` в ruantiblock...

**Comment by vit9696** [comment]
@gSpotx2f, а можно ограничиться созданием репозитория и мёрджем патчей от окружающих? Просто хотелось бы воспользоваться "узнаваемым" местом/именем, куда можно было класть доменные имена. Если времени на просмотр pull request нет совсем, то с ревью изменений могу помочь и мёрджем патчей могу помочь.

**Comment by gSpotx2f** [comment]
@vit9696, цель этого репозитория - всего лишь предоставление готовых конфигов, созданных из реестра РКН. Т.е. любой пользователь может повторить конфигурацию на своём роутере в настройках ruantiblock (с выгрузкой и парсингом реестра), вообще не используя данный репозиторий. Я включил этот репо в стандартный конфиг ruantiblock исключительно в интересах пользователей обладающих девайсами с малым количеством оперативки (<256Мб.), ибо полноценная выгрузка и обработка реестра, на таких устройствах, часто приводит к краху из-за нехватки памяти. Мой роутер обновляет блэклист раз в сутки и коммитит в этот репо, но не могу гарантировать, что так будет всегда. Ruantiblock задумывался именно как инструмент для автоматизации обработки реестра из сторонних источников на роутере пользователя, ведение собственных списков блокировок - это совсем другая тема...

**Comment by vit9696** [comment]
Ок.

> Мой роутер обновляет блэклист раз в сутки и коммитит в этот репо, но не могу гарантировать, что так будет всегда. Ruantiblock задумывался именно как инструмент для автоматизации обработки реестра из сторонних источников на роутере пользователя, ведение собственных списков блокировок - это совсем другая тема…

А почему для этого не задействовать GitHub Actions? Они бесплатные и будут работать независимо от роутера.

**Comment by gSpotx2f** [comment]
Если роутер сам выполняет обработку реестра, то можно отслеживать использование памяти, т.е. насколько парсер работоспособен на реальном устройстве с ограниченными возможностями (реестр постоянно растёт, а размер оперативной памяти, к сожалению, нет :)). Я думал про Actions, но мне сейчас необходима обработка реестра именно на роутере, в реальных условиях. А вообще, Actions хорошая тема для слабых девайсов,  можно переложить тяжёлую работу с роутера на GitHub.
