### ISSUE TITLE
rutracker error

### ISSUE THREAD

**Issue by routir** [gSpotx2f/ruantiblock_blacklist#3]
Any link on rutracker.net leads to 403: invalid IP 0.0.0.0

**Comment by gSpotx2f** [comment]
Не подтверждаю, rutracker.net резолвится без проблем (188.114.96.1, 188.114.97.1). Шифрование DNS у вас настроено?

**Comment by routir** [comment]
Тут дело не в шифрованиее, видимо WARP+ чудит, после перезапуска интерфейса работает несколько кликов и опять ошибка.

**Comment by gSpotx2f** [comment]
>видимо WARP+ чудит

Тогда в чём суть вашего тикета здесь? Какое это имеет отношение к данному репозиторию?
