### ISSUE TITLE
zapret-info

### ISSUE THREAD

**Issue by spvkgn** [gSpotx2f/ruantiblock_blacklist#4]
Репозиторий zapret-info две недели не обновляется и неизвестно будет ли. Возможно, есть смысл добавить другой рабочий источник выгрузок доступный на github - https://github.com/fz139/vigruzki ?

**Comment by gSpotx2f** [comment]
>Репозиторий zapret-info две недели не обновляется и неизвестно будет ли.

РКН не обновлял выгрузку с 4 по 18 марта. Сейчас выгрузка возобновилась, но zapret-info действительно пока не обновляется. Будет очень жаль, если больше не будет обновлений. Это самый старый и стабильный источник реестра, буквально с самого начала с 2012 года...

>Возможно, есть смысл добавить другой рабочий источник выгрузок доступный на github - https://github.com/fz139/vigruzki ?

Пока переключил на [rublacklist.net](https://reestr.rublacklist.net/article/api/). Проблема источника https://github.com/fz139/vigruzki в том, что реестр разбит на файлы по 100мб., т.е. в будущем будут появляться новые файлы (dump.xml.03, dump.xml.04 и т.д.), которые нужно постоянно отслеживать и вручную добавлять в конфиг парсера.

**Comment by gSpotx2f** [comment]
С zapret-info всё оказалось проще... Проблема с обновлениями только на [github](https://github.com/zapret-info/z-i), на [зеркале](https://app.assembla.com/spaces/z-i/git/source/master) всё штатно обновляется с 18-го марта.
