### ISSUE TITLE
готовые списки доменов для user entries

### ISSUE THREAD

**Issue by spvkgn** [gSpotx2f/ruantiblock_blacklist#5]
Было бы здорово добавить возможность добавлять user entries из готовых списков доменов, например https://github.com/antonme/ipnames/raw/master/dns-openai.txt
Какой-нибудь текстовый файл с перечнем ссылок на списки или что-то подобное?

**Comment by gSpotx2f** [comment]
Добавил параметр `USER_ENTRIES_REMOTE` для подгрузки удалённых файлов в 1.1. Файлы должны быть в формате файла `user_entries`. Записи из удалённых файлов добавляются также как и из локального, т.е. без проверок на повторы и оптимизаций, поэтому лучше слишком не увлекаться большими списками...
Эта опция также добавлена в сам [ruantiblock](https://github.com/gSpotx2f/ruantiblock_openwrt/commit/edb43ea74c71b7d4e99d8cc63859c6f7a9767ba3) (на странице настроек блэклиста).
