### ISSUE TITLE
Re:filter source

### ISSUE THREAD

**Issue by spvkgn** [gSpotx2f/ruantiblock_blacklist#8]
Возможно, есть смысл добавить этот источник? Есть готовые списки доменов и ip
https://github.com/1andrevich/Re-filter-lists
Подробнее на [хабре](https://habr.com/ru/articles/850292/)

**Comment by gSpotx2f** [comment]
Проблема в том, что там нет реестра, т.е. записей `ip-адрес(а), домен`. В одном файле все ip из реестра, в другом файле все домены. Нет информации о том как они соотносятся между собой (какие ip в реестре к каким записям доменов принадлежат). А без этого невозможен точный обход блокировок, нужны именно **записи** из реестра (как в [zapret-info](https://github.com/zapret-info/z-i/blob/master/dump.csv), например). Парсер обрабатывая реестр вытаскивает из записей домены в конфиг dnsmasq (ip из этих записей не нужны). Но есть записи реестра в которых нет домена (заблокированные по ip или диапазоны ip) и вот из этих записей берутся ip-адреса и добавляются сразу в nftables. Получается довольно точная фильтрация и домены всегда актуальны: если сайт сменил ip, то в реестре останется старый ip (который был на момент внесения, ркн их не обновляет), а DPI у провайдера (или ТСПУ) определяет именно домен из поля SNI и по нему блокирует. Поэтому я считаю, что обход по спискам ip из реестра - не эффективен, к тому же на одном ip может сидеть куча доменов и все они, за компанию, автоматически попадают в обход.
